name: Lint

on:
  push:
    branches: [main]
  pull_request:

permissions: {}

jobs:
  lint-actions:
    name: GitHub Actions audit
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Run actionlint
        uses: rhysd/actionlint@v1.7.11

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@v0.5.2
        with:
          advanced-security: false
          persona: pedantic
